# Generated by Django 3.0.7 on 2020-06-08 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=200)),
                ('altor_livro', models.CharField(max_length=200)),
                ('ano_livro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('resumo_livro', models.TextField()),
            ],
        ),
    ]
