# Generated by Django 3.0.7 on 2020-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quntia_livro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
