# Generated by Django 3.0.7 on 2020-06-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20200610_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='quntia_livro',
            new_name='quantia_livro',
        ),
    ]
