# Generated by Django 3.0.7 on 2020-06-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_bok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='username',
        ),
    ]
