# Generated by Django 3.0.7 on 2020-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20200616_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Emprestimo',
        ),
    ]
